Hello Microverse Project pull request
Mikey1-nuel/Hello-Microverse-project pull request #1
Opened 2023-02-15 01:48 UTC by Mikey1-nuel

2023-02-15 03:04 UTC, AbayomiOlaoye requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @Mikey1-nuel  :wave: , 

Good job with this milestone so far!
There are just few more issues to work on before moving onto the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- No linter error :heavy_check_mark: 
- Good implementation :heavy_check_mark: 

## Required Changes ♻️

- [ ] _Check the comments under the review._

- Since I do not have access to the ReadMe in this **PR** in question, I have tried to get explicitly edited screenshots to suggest how you can improve on your code and project submission.

- [ ] Below is a snapshot of your ReadMe file and some suggested changes:

![image](https://user-images.githubusercontent.com/99715640/218915767-ea8b33bb-ca87-4755-960d-dbf5bcd4e860.png)

- You are almost done with this project, @Mikey1-nuel  :smile: : 
- - [ ] :+1: Like I said, you have made a brilliant effort to get this up and running you still need to give your nice README.md some more time and attention so that you can have contents that make your project look professional to visitors or users.
  - [ ] * The only **optional** section is FAQ.
  * You can also delete the live demo section since you are not deploying your application now or you just let visitors know that it is not ready by writing `N/A` - Not Available instead of adding an irrelevant link. That will improve your user experience,
  * Kindly add more descriptive message to **About your project** and every other section that you have in the ReadMe..
  * Kindly add some key features of your code in the ReadMe to change the template 
  * Also, kindly include the 2-3 **Future features** of the project in the future project instead of the template input there. This doesn't add any value to your visitors and it is not a professional practice to claim code that lacks customization.
* It will be more customized to **remove the section description**, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project." should be removed and filled in with their custom content.
* Your `LICENSE`  (`MIT`) link is not working at the moment and I think that is due to the absence of `LICENSE` file in your root folder. Kindly add it and ensure it leads to the appropriate resource. This offers valuable information to your users about how to use or share your intellectual work.
* In Summary, kindly remove all the elements in read box

Keep doing an amazing job, Micronaut! :clap: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 03:04 UTC, AbayomiOlaoye commented on index.html
> +	<title>Document</title>
- [ ] Kindly include a more descriptive title for your page. It will be okay if you can make it a habit as it is also a best practice that enhances how Search Engines rank your page and increase access to your content. :wink: - `Document` is too vague and generic. How about something like `Hello page` or something similar that suggests what the page is about?

2023-02-16 08:29 UTC, AlphaNtihinduka requested changes
## Hi @Mikey1-nuel 🙋‍♂️

Good job working on implementing the changes required by the previous reviewer. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is not yet professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- [ ] Use the inline comments. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-02-16 08:29 UTC, AlphaNtihinduka commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] Your LICENSE (MIT) link is not working at the moment and I think that is due to the wrong extension of the LICENSE file in your root folder. Kindly edit it and ensure it leads to the appropriate resource. This offers valuable information to your users about how to use or share your intellectual work ☺️ .

2023-02-16 08:29 UTC, AlphaNtihinduka commented on README.md
- [ ] [OPTIONAL] So far the README is almost professional. However, there are a few changes to apply. I suggest that you add the setup, installation, and run test commands. You stated that the visitor should run the command ☺️ but you didn't provide the command. Kindly ensure to give the command guideline 👍 .

2023-02-16 10:23 UTC, Mikey1-nuel commented
Hi  ***@***.***,*
*The project doesn't have many details in it. I was wondering if maybe it's
okay if I remove the install, deployment, and run test command area.*

On Thu, Feb 16, 2023 at 9:29 AM NTIHINDUKA ALPHA ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @Mikey1-nuel <https://github.com/Mikey1-nuel> 🙋‍♂️
>
> Good job working on implementing the changes required by the previous
> reviewer. You have done the design to do the expectation and incredibly
> well. 👏
>
> TO HIGHLIGHT:
>
>    - Your project is professional ✅
>    - Professional README file 💯
>    - Your PR is not yet professional ✅
>    - Well-structured files ✅
>
> STATUS: Required Changes ♻️
>
> [image: close]
> <https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif>
> Required changes ♻️
>
>    - Use the inline comments.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread or slack
> channel if something is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> HAPPY CODING AND GOOD LUCK 🤞 🍀
> ------------------------------
>
> In README.md
> <https://github.com/Mikey1-nuel/Hello-Microverse-project/pull/1#discussion_r1108149497>
> :
>
> >
>
>  <p align="right">(<a href="#readme-top">back to top</a>)</p>
>
>
>
> -<!-- LICENSE -->
>
>
>
>  ## 📝 License <a name="license"></a>
>
>
>
>  This project is [MIT](./LICENSE) licensed.
>
>
>
>    - Your LICENSE (MIT) link is not working at the moment and I think
>    that is due to the wrong extension of the LICENSE file in your root folder.
>    Kindly edit it and ensure it leads to the appropriate resource. This offers
>    valuable information to your users about how to use or share your
>    intellectual work ☺️ .
>
> ------------------------------
>
> In README.md
> <https://github.com/Mikey1-nuel/Hello-Microverse-project/pull/1#discussion_r1108154135>
> :
>
> >  ### Setup
>
>
>
>  Clone this repository to your desired folder:
>
>
>
> -<!--
>
> -Example commands:
>
> +- Copy the ssh code to the project repository.
>
> +- Clone this repository using a git command machine to add the file locally to your desired folder.
>
> +- Open the folder in your code editor to enable you edit the file as you desire.
>
>
>
> -```sh
>
> -  cd my-folder
>
> -  git clone ***@***.***:myaccount/my-project.git
>
> -```
>
> ---->
>
>
>
>  ### Install
>
>
>
>  Install this project with:
>
>
>
> -<!--
>
> -Example command:
>
> +cd Hello-Microverse-project
>
>
>
> -```sh
>
> -  cd my-project
>
> -  gem install
>
> -```
>
> ---->
>
>
>
>  ### Usage
>
>
>
>
>
>    - [OPTIONAL] So far the README is almost professional. However, there
>    are a few changes to apply. I suggest that you add the setup, installation,
>    and run test commands. You stated that the visitor should run the command
>    ☺️ but you didn't provide the command. Kindly ensure to give the
>    command guideline 👍 .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mikey1-nuel/Hello-Microverse-project/pull/1#pullrequestreview-1300959717>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZRJAPRA6LDQBPRJCE5OW23WXXQNXANCNFSM6AAAAAAU4IK7PE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-16 14:24 UTC, roshan-bajgain approved these changes
Hi @Mikey1-nuel, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- GitHub flow is followed. ✔️
- PR has a good title and summary. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 14:34 UTC, closed without merging